### ISSUE TITLE
Pisces modal

### ISSUE THREAD

**Issue by kvothe1387** [kvothe1387/Horoscope-Dreems#12]
Pisces card modal including sign with least compatibility, most likely way to die, 1-3 negative traits, and top challenge

**Comment by jesseunderwood** [comment]
As a Pisces, the least compatible would be Geminis or Libras. Their most likely way to die would be by human sacrifice. Some negative traits that Pisces have is they can be easily influenced by their surroundings, careless, rash and ill-disciplined, and Inability to confront reality due to an absence of confidence. Their top challenge can include empathy, boundary setting, self-awareness, indecisiveness.
